<?php

declare(strict_types=1);

namespace Maetva\DhlExpress\ExpressRateBook;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'docTypeRef_ProcessShipmentRequestType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ProcessShipmentRequestType',
            'docTypeRef_ClientDetailType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ClientDetailType2',
            'Request' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Request',
            'ServiceHeaderType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ServiceHeaderType',
            'docTypeRef_Content' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_Content',
            'docTypeRef_DangerousGoods' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_DangerousGoods',
            'docTypeRef_RequestedShipmentType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RequestedShipmentType',
            'docTypeRef_ShipmentInfoType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ShipmentInfoType',
            'ShipmentPrepaidTotalCharge' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ShipmentPrepaidTotalCharge',
            'docTypeRef_InternationDetailType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_InternationDetailType',
            'docTypeRef_CommoditiesType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_CommoditiesType',
            'ExportDeclaration' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ExportDeclaration',
            'ExportLineItems' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ExportLineItems',
            'ExportLineItemType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ExportLineItemType',
            'AdditionalInformation' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\AdditionalInformation',
            'ItemReferences' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ItemReferences',
            'ItemReference' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ItemReference',
            'CustomsPaperworks' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomsPaperworks',
            'CustomsPaperwork' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomsPaperwork',
            'InvoiceDeclarationTexts' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\InvoiceDeclarationTexts',
            'InvoiceDeclarationText' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\InvoiceDeclarationText',
            'CustomsDocuments' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomsDocuments',
            'CustomsDocument' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomsDocument',
            'InvoiceSignatureDetails' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\InvoiceSignatureDetails',
            'OtherCharges' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\OtherCharges',
            'OtherCharge' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\OtherCharge',
            'Remarks' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Remarks',
            'Remark' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Remark',
            'CustomerDataTextEntries' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomerDataTextEntries',
            'CustomerDataTextEntry' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomerDataTextEntry',
            'InvoiceReferences' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\InvoiceReferences',
            'InvoiceReference' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\InvoiceReference',
            'docTypeRef_OnDemandDeliveryOptions' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_OnDemandDeliveryOptions',
            'docTypeRef_ShipType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ShipType',
            'docTypeRef_ContactInfoType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ContactInfoType',
            'docTypeRef_ContactInfoType1' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ContactInfoType1',
            'docTypeRef_ContactType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ContactType',
            'docTypeRef_ContactType1' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ContactType1',
            'docTypeRef_AddressType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_AddressType',
            'docTypeRef_AddressType1' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_AddressType1',
            'docTypeRef_RegistrationNumbers' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RegistrationNumbers',
            'docTypeRef_RegistrationNumber' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RegistrationNumber',
            'docTypeRef_BankDetails' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_BankDetails',
            'docTypeRef_BankDetail' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_BankDetail',
            'docTypeRef_PackagesType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_PackagesType',
            'docTypeRef_RequestedPackagesType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RequestedPackagesType',
            'docTypeRef_DimensionsType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_DimensionsType',
            'Billing' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Billing',
            'Services' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Services',
            'Service' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Service',
            'PaymentMethods' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\PaymentMethods',
            'DocumentImages' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocumentImages',
            'DocumentImage' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocumentImage',
            'LabelOptions' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\LabelOptions',
            'CustomerLogo' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomerLogo',
            'CustomerBarcode' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\CustomerBarcode',
            'DetachOptions' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DetachOptions',
            'ShipmentReferences' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ShipmentReferences',
            'ShipmentReferenceType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ShipmentReferenceType',
            'BespokeLabelData' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\BespokeLabelData',
            'LabelBarcodes' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\LabelBarcodes',
            'LabelBarcode' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\LabelBarcode',
            'LabelTextEntries' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\LabelTextEntries',
            'LabelTextEntry' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\LabelTextEntry',
            'PackageReferences' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\PackageReferences',
            'PackageReferenceType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\PackageReferenceType',
            'docTypeRef_ShipmentNotifications' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ShipmentNotifications',
            'docTypeRef_ShipmentNotification' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ShipmentNotification',
            'docTypeRef_RateRequestType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RateRequestType',
            'docTypeRef_ClientDetailType3' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ClientDetailType3',
            'RequestType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\RequestType',
            'docTypeRef_RequestedShipmentType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RequestedShipmentType2',
            'docTypeRef_ShipType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ShipType2',
            'docTypeRef_AddressType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_AddressType2',
            'docTypeRef_PackagesType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_PackagesType2',
            'docTypeRef_RequestedPackagesType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RequestedPackagesType2',
            'docTypeRef_WeightType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_WeightType',
            'docTypeRef_DimensionsType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_DimensionsType2',
            'Billing2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Billing2',
            'Services2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Services2',
            'Service2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Service2',
            'ProductsAndServices2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ProductsAndServices2',
            'ProductAndServices' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ProductAndServices',
            'LandedCostType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\LandedCostType',
            'ItemsType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ItemsType',
            'ItemType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ItemType',
            'GoodsCharacteristicsType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\GoodsCharacteristicsType',
            'GoodsCharacteristicType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\GoodsCharacteristicType',
            'AdditionalQuantityDefinitionsType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\AdditionalQuantityDefinitionsType',
            'AdditionalQuantityDefinitionType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\AdditionalQuantityDefinitionType',
            'ShipmentMonetaryAmountType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ShipmentMonetaryAmountType',
            'ChargesType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ChargesType',
            'docTypeRef_DeleteResponseType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_DeleteResponseType',
            'ResponseType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ResponseType',
            'docTypeRef_NotificationType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_NotificationType',
            'docTypeRef_DeleteRequestType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_DeleteRequestType',
            'docTypeRef_ClientDetailType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ClientDetailType',
            'docTypeRef_RateResponseType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_RateResponseType',
            'docTypeRef_ProviderType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ProviderType',
            'docTypeRef_NotificationType3' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_NotificationType3',
            'docTypeRef_WarningType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_WarningType',
            'docTypeRef_ServiceType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ServiceType',
            'TotalNet' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\TotalNet',
            'Charges' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Charges',
            'docTypeRef_TotalNetType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_TotalNetType',
            'docTypeRef_TotalChargeTypes' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_TotalChargeTypes',
            'TotalChargeType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\TotalChargeType',
            'docTypeRef_ChargesType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ChargesType',
            'docTypeRef_ChargeType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ChargeType',
            'ChargeBreakdown' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ChargeBreakdown',
            'Breakdown' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Breakdown',
            'docTypeRef_ItemsType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ItemsType',
            'docTypeRef_ItemType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ItemType',
            'Notification' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\Notification',
            'docTypeRef_ServiceAreaType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ServiceAreaType',
            'docTypeRef_ExchangeRateType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ExchangeRateType',
            'ExchangeRate' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ExchangeRate',
            'docTypeRef_ShipmentDetailType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_ShipmentDetailType',
            'docTypeRef_Response' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_Response',
            'docTypeRef_NotificationType2' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_NotificationType2',
            'docTypeRef_PackagesResultsType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_PackagesResultsType',
            'docTypeRef_PackageResultType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_PackageResultType',
            'docTypeRef_LabelImageType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_LabelImageType',
            'docTypeRef_Documents' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_Documents',
            'docTypeRef_Document' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_Document',
            'docTypeRef_TotalNet' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_TotalNet',
            'docTypeRef_Charges' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_Charges',
            'docTypeRef_OriginServiceAreaType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_OriginServiceAreaType',
            'docTypeRef_DestinationServiceAreaType' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_DestinationServiceAreaType',
            'ServiceHandlingFeatureCodes' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\ServiceHandlingFeatureCodes',
            'BarcodeInfo' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\BarcodeInfo',
            'docTypeRef_TrackingNumberBarcodes' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_TrackingNumberBarcodes',
            'docTypeRef_TrackingNumberBarcode' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\DocTypeRef_TrackingNumberBarcode',
            'EstimatedDeliveryDate' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\EstimatedDeliveryDate',
            'PickupDetails' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\PickupDetails',
            'QRCode' => '\\Maetva\\DhlExpress\\ExpressRateBook\\StructType\\QRCode',
        ];
    }
}
